#!/usr/bin/env python3
"""SA-6 helper: inject results.json numbers into paper/results_macros.tex.

Every reported number in the paper is a macro defined here, so each claim traces
to a value in results.json (the SA-6 validation criterion). Run after SA-5.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from drc.utils import load_json, path


def fmt(x, nd=2):
    try:
        return f"{float(x):.{nd}f}"
    except (TypeError, ValueError):
        return "TBD"


def main(results_json=None):
    results_json = results_json or path("results", "results.json")
    r = load_json(results_json)
    h1, h2, h3, h4 = r["H1"], r["H2"], r["H3"], r["H4"]
    om = r["outcome_matrix"]
    power = r.get("power", {})

    macros = {
        "NRuns": r.get("n_runs", 18),
        "NCheckpoints": r.get("n_observations", 108),
        "HoneGap": fmt(h1["median_gap_pct"]),
        "HoneP": fmt(h1["p_value"], 4),
        "HoneSupported": "supported" if h1["supported"] else "not supported",
        "HtwoP": fmt(h2["p_value"], 4),
        "HtwoSupported": "supported" if h2["supported"] else "not supported",
        "HthreeBest": str(h3.get("best_metric")),
        "HthreeBestSpearman": fmt(h3["per_metric"].get(h3.get("best_metric"), {}).get("mean_spearman", "nan")),
        "HthreeSupported": "supported" if h3["supported"] else "not supported",
        "HfourCompRMSE": fmt(h4["composite_rmse"], 3),
        "HfourBaseRMSE": fmt(h4["baseline_rmse"], 3),
        "HfourRel": fmt(h4["relative_improvement"] * 100, 1),
        "HfourSupported": "supported" if h4["supported"] else "not supported",
        "OutcomeTitle": om["title"],
        "OutcomeAngle": om["angle"],
        "PowerHone": fmt(power.get("H1_power_delta10_sigma15", "nan")),
    }

    out = path("paper", "results_macros.tex")
    lines = ["% Auto-generated by scripts/fill_paper.py — do not edit by hand."]
    for k, v in macros.items():
        lines.append(f"\\newcommand{{\\{k}}}{{{v}}}")
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {len(macros)} macros -> {out}")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else None)
